name: maven
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  maven:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify site
      - uses: actions/upload-artifact@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          name: maven-target-${{ matrix.os }}
          path: target/
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package-${{ matrix.os }}
          path: staging

  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Event File
        path: ${{ github.event_path }}
